os:
  - linux
  - osx
  - windows

dist: trusty
sudo: false

language: node_js
# Also update "Global dependencies" in `README.md` to match tested Node.js versions.
node_js:
  - 10
  - 12
  - 14
  - node

cache:
  directories:
    - "$HOME/.npm"

install:
  # Install `yarn` to be used in e2e tests.
  - npm install --global yarn;
  # Run `npm install`, if `npm ci` fails, to work around old npm versions' not supporting `npm ci`.
  - npm ci || npm install;

script:
  - npm test;
